package fussen.yu.news;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fussen.yu.news.User;
import fussen.yu.news.Sport;

import fussen.yu.news.UserDao;
import fussen.yu.news.SportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig sportDaoConfig;

    private final UserDao userDao;
    private final SportDao sportDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        sportDaoConfig = daoConfigMap.get(SportDao.class).clone();
        sportDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        sportDao = new SportDao(sportDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Sport.class, sportDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        sportDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SportDao getSportDao() {
        return sportDao;
    }

}
