package fussen.yu.news;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String nickName;
    /** Not-null value. */
    private String avatarUrl;
    /** Not-null value. */
    private String mobile;
    /** Not-null value. */
    private String gender;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String nickName, String avatarUrl, String mobile, String gender) {
        this.id = id;
        this.nickName = nickName;
        this.avatarUrl = avatarUrl;
        this.mobile = mobile;
        this.gender = gender;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNickName() {
        return nickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /** Not-null value. */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /** Not-null value. */
    public String getMobile() {
        return mobile;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /** Not-null value. */
    public String getGender() {
        return gender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGender(String gender) {
        this.gender = gender;
    }

}
